# -*- coding: utf-8 -*-
"""testing_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17anpz4jSq1DsOGySxGBeJm8OYgVJWEkD
"""

# Full Colab pipeline with improved ROI extraction (class-wise folders)
from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
import torch
import torch.nn as nn
import numpy as np
from torchvision import transforms, models
from PIL import Image
import matplotlib.pyplot as plt

# ==== Paths ====
BASE_FOLDER = '/content/drive/MyDrive/PCB_DATASET'
PCB_USED_PATH = os.path.join(BASE_FOLDER, "PCB_USED")   # Golden/reference images
MODEL_PATH = os.path.join(BASE_FOLDER, "output/efficientnet_b4_best.pth")
ROI_BASE = os.path.join(BASE_FOLDER, "Pipeline_ROIs")            # will create ROIs/<defect_type>/
SUBTRACTED_SAVE = os.path.join(BASE_FOLDER, "subtracted_images_colab")  # optional
os.makedirs(ROI_BASE, exist_ok=True)
os.makedirs(SUBTRACTED_SAVE, exist_ok=True)

# Example test image (change as needed)
TEST_IMG_PATH = os.path.join(BASE_FOLDER, "images/Short/11_short_10.jpg")
IMAGES_FOLDER = os.path.join(BASE_FOLDER, "images")  # for batch processing

# ==========================================
# 1️⃣ Load Model (unchanged)
# ==========================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

checkpoint = torch.load(MODEL_PATH, map_location=device)
classes = checkpoint['classes']
num_classes = len(classes)

model = models.efficientnet_b4(pretrained=False)
model.classifier[1] = nn.Linear(model.classifier[1].in_features, num_classes)
model.load_state_dict(checkpoint['model_state_dict'])
model = model.to(device)
model.eval()

class_to_idx = checkpoint.get('class_to_idx', None)
idx_to_class = {v: k for k, v in class_to_idx.items()} if class_to_idx else None
print("✅ Model loaded with classes:", idx_to_class if idx_to_class else classes)

transform = transforms.Compose([
    transforms.Resize((128,128)),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5], [0.5,0.5,0.5])
])


# ==========================================
# Utility: find reference (case-insensitive)
# ==========================================
def find_reference_file(pcb_used_folder, pcb_id):
    for f in os.listdir(pcb_used_folder):
        if f.lower().startswith(pcb_id.lower()) and f.lower().endswith(('.jpg', '.jpeg', '.png')):
            return os.path.join(pcb_used_folder, f)
    return None


# ==========================================
# 2️⃣ Image Subtraction (with mask cleaning)
# ==========================================
def subtract_images(defect_img_path, pcb_used_folder, save_mask_path=None):
    img_name = os.path.basename(defect_img_path)

    # Load defect image
    defect_gray = cv2.imread(defect_img_path, cv2.IMREAD_GRAYSCALE)
    defect_color = cv2.imread(defect_img_path)
    if defect_gray is None or defect_color is None:
        raise ValueError(f"❌ Could not load defect image: {defect_img_path}")

    # Extract PCB number
    pcb_number = img_name.split("_")[0] + ".jpg"

    # Case-insensitive reference search
    ref_file = None
    for f in os.listdir(pcb_used_folder):
        if f.lower() == pcb_number.lower():
            ref_file = os.path.join(pcb_used_folder, f)
            break
    if ref_file is None:
        raise ValueError(f"❌ No reference PCB found for {pcb_number} in {pcb_used_folder}")

    # Load reference
    ref_img = cv2.imread(ref_file, cv2.IMREAD_GRAYSCALE)
    if ref_img is None:
        raise ValueError(f"❌ Could not load reference image: {ref_file}")

    # Resize if needed
    if ref_img.shape != defect_gray.shape:
        ref_img = cv2.resize(ref_img, (defect_gray.shape[1], defect_gray.shape[0]))

    # --- Preprocess both images ---
    defect_blur = cv2.GaussianBlur(defect_gray, (5,5), 0)
    ref_blur = cv2.GaussianBlur(ref_img, (5,5), 0)

    # --- Subtract ---
    subtracted = cv2.absdiff(defect_blur, ref_blur)

    # --- Adaptive thresholding (better for variable defects) ---
    binary = cv2.adaptiveThreshold(
        subtracted, 255,
        cv2.ADAPTIVE_THRESH_MEAN_C,
        cv2.THRESH_BINARY,
        35,  # block size (should be odd)
        -5   # constant, adjust to make detection stricter/looser
    )

    # --- Morphological cleaning ---
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (5,5))
    cleaned = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel, iterations=1)
    cleaned = cv2.morphologyEx(cleaned, cv2.MORPH_CLOSE, kernel, iterations=1)
    cleaned = cv2.dilate(cleaned, kernel, iterations=2)

    if save_mask_path:
        cv2.imwrite(save_mask_path, cleaned)

    return defect_color, cleaned


# ==========================================
# 3️⃣ ROI Extraction — class-wise like VS Code
# ==========================================
def extract_rois_and_save(orig_img, mask, save_base_folder, base_name, defect_type=None,
                          min_area=200, min_w=10, min_h=10):
    """
    Crops ROIs from orig_img using mask contours and saves them under:
       save_base_folder/<defect_type>/<base_name>_roi{n}.png
    If defect_type is None, saves directly under save_base_folder.
    Returns list of saved ROI paths.
    """
    # Determine output folder (mimic your VS Code layout: ROIs/<defect_type>/)
    if defect_type:
        roi_sub_folder = os.path.join(save_base_folder, defect_type)
    else:
        roi_sub_folder = save_base_folder
    os.makedirs(roi_sub_folder, exist_ok=True)

    # findContours compatibility (robust)
    contours_info = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contours = contours_info[0] if len(contours_info) == 2 else contours_info[1]

    roi_paths = []
    roi_count = 0

    for cnt in contours:
        x, y, w, h = cv2.boundingRect(cnt)
        area = cv2.contourArea(cnt)

        # Filter noise by area and dimensions (tune these if needed)
        if area < min_area or w < min_w or h < min_h:
            continue

        # Ensure bounding box inside image
        x1 = max(0, x); y1 = max(0, y)
        x2 = min(orig_img.shape[1], x + w)
        y2 = min(orig_img.shape[0], y + h)

        # Crop ROI (color)
        roi = orig_img[y1:y2, x1:x2]
        if roi.size == 0:
            continue

        roi_filename = f"{os.path.splitext(base_name)[0]}_roi{roi_count}.png"
        roi_save_path = os.path.join(roi_sub_folder, roi_filename)
        cv2.imwrite(roi_save_path, roi)
        roi_paths.append(roi_save_path)
        roi_count += 1

    return roi_paths


# ==========================================
# 4️⃣ Model Prediction on ROI (same as before)
# ==========================================
def predict_roi(roi_path, model, class_names, transform, device):
    img = Image.open(roi_path).convert("RGB")
    img_tensor = transform(img).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(img_tensor)
        probs = torch.softmax(output, dim=1).cpu().numpy()[0]
        top3_idx = probs.argsort()[-3:][::-1]

    top3 = [(class_names[i], float(probs[i])) for i in top3_idx]
    label, conf = top3[0]

    # Show ROI + Prediction
    plt.imshow(img)
    plt.axis("off")
    plt.title(f"Predicted: {label} ({conf:.2f})")
    plt.show()

    return label, conf, top3


# ==========================================
# 5️⃣ Single-image pipeline runner (saves class-wise ROIs)
# ==========================================
def process_single_image(img_path, save_mask_folder=SUBTRACTED_SAVE, roi_base=ROI_BASE):
    base_name = os.path.basename(img_path)
    defect_type = os.path.basename(os.path.dirname(img_path))  # e.g., "Spurious_copper"

    # Subtraction (save mask for debugging)
    mask_save_path = os.path.join(save_mask_folder, f"{os.path.splitext(base_name)[0]}_mask.png")
    defect_color, mask = subtract_images(img_path, PCB_USED_PATH, save_mask_path=mask_save_path)

    # ROI extraction and save under ROIs/<defect_type>/
    roi_paths = extract_rois_and_save(defect_color, mask, roi_base, base_name, defect_type=defect_type)

    print(f"✅ Extracted {len(roi_paths)} ROIs for {base_name} — saved to {os.path.join(roi_base, defect_type)}")

    # Predict on each ROI
    for roi_path in roi_paths:
        label, conf, top3 = predict_roi(roi_path, model, classes, transform, device)
        print("✅ Final Prediction:", label, conf)
        print("Top-3 Predictions:", top3)
        print("----")

    return roi_paths


# ==========================================
# 6️⃣ Batch runner: process everything under images/
#    (will mimic your VS Code flow: for each defect class folder)
# ==========================================
def process_images_folder(images_folder):
    for defect_type in os.listdir(images_folder):
        defect_type_path = os.path.join(images_folder, defect_type)
        if not os.path.isdir(defect_type_path):
            continue

        for fname in os.listdir(defect_type_path):
            if not fname.lower().endswith(('.jpg', '.jpeg', '.png')):
                continue
            img_path = os.path.join(defect_type_path, fname)
            try:
                process_single_image(img_path)
            except Exception as e:
                print(f"❌ Skipping {img_path}: {e}")


# ==========================================
# 🔥 Usage
# ==========================================
# Single image:
# process_single_image(TEST_IMG_PATH)

# Batch (all images):
# process_images_folder(IMAGES_FOLDER)

# Example run now:
process_single_image(TEST_IMG_PATH)

