# -*- coding: utf-8 -*-
"""infosys_pcb_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YQ9MZxFtmCcWqhikOt7CksLWp1UuEExF
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# Paths
CSV_PATH = '/content/drive/MyDrive/PCB_DATASET/dataset_labels.csv'
ROIS_ROOT = '/content/drive/MyDrive/PCB_DATASET/ROIs'
OUT_DIR = '/content/drive/MyDrive/PCB_DATASET/output'
import os
os.makedirs(OUT_DIR, exist_ok=True)

import pandas as pd
from sklearn.model_selection import train_test_split

# ---- Stratified 80/20 Split ----
df = pd.read_csv(CSV_PATH)
assert 'image_name' in df.columns and 'label' in df.columns, "CSV must have image_name,label"

train_df, val_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df['label'],   # ensures per-class split
    random_state=42
)

print("Train size:", len(train_df), "Val size:", len(val_df))
print("Class distribution in Train:", train_df['label'].value_counts())
print("Class distribution in Val:", val_df['label'].value_counts())

# Save split CSVs for reproducibility
train_csv = os.path.join(OUT_DIR, "train_labels.csv")
val_csv = os.path.join(OUT_DIR, "val_labels.csv")
train_df.to_csv(train_csv, index=False)
val_df.to_csv(val_csv, index=False)

from torch.utils.data import Dataset
from PIL import Image
import torch
import os

class PCBRoiDataset(Dataset):
    def __init__(self, csv_file, rois_root, transform=None):
        self.df = pd.read_csv(csv_file)
        self.rois_root = rois_root
        self.transform = transform
        self.classes = sorted(self.df['label'].unique().tolist())
        self.class_to_idx = {c:i for i,c in enumerate(self.classes)}

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_fname = row['image_name']
        label_name = row['label']
        img_path = os.path.join(self.rois_root, label_name, img_fname)
        image = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        label = self.class_to_idx[label_name]
        return image, label

from torchvision import transforms
from torch.utils.data import DataLoader
from collections import Counter
from torch.utils.data import WeightedRandomSampler

train_transform = transforms.Compose([
    transforms.Resize((128,128)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5],[0.5,0.5,0.5])
])
val_transform = transforms.Compose([
    transforms.Resize((128,128)),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5],[0.5,0.5,0.5])
])

train_dataset = PCBRoiDataset(train_csv, ROIS_ROOT, transform=train_transform)
val_dataset   = PCBRoiDataset(val_csv, ROIS_ROOT, transform=val_transform)

num_classes = len(train_dataset.classes)
print("Classes:", train_dataset.classes)

# Handle imbalance (WeightedRandomSampler)
train_labels = [train_dataset.class_to_idx[row['label']] for _, row in train_dataset.df.iterrows()]
counts = Counter(train_labels)
class_weights = {cls: 1.0/counts[cls] for cls in counts}
sample_weights = [class_weights[l] for l in train_labels]
sampler = WeightedRandomSampler(weights=sample_weights, num_samples=len(sample_weights), replacement=True)

batch_size = 8   # reduce because EfficientNet-B4 is heavier
train_loader = DataLoader(train_dataset, batch_size=batch_size, sampler=sampler, num_workers=2)
val_loader   = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=2)

import torch
import torch.nn as nn
from torchvision import models

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Device:", device)

# Use EfficientNet-B4 pretrained
try:
    weights = models.EfficientNet_B4_Weights.IMAGENET1K_V1
    model = models.efficientnet_b4(weights=weights)
except:
    model = models.efficientnet_b4(pretrained=True)

# Replace classifier
in_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(in_features, num_classes)
model = model.to(device)

# Loss & Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import CosineAnnealingLR
from torchvision import transforms
import time, os
from torch.amp import autocast, GradScaler

# ==== DATA AUGMENTATIONS ====
train_transforms = transforms.Compose([
    transforms.RandomResizedCrop(128, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

val_transforms = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5])
])

# ==== CRITERION (label smoothing) ====
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

# ==== OPTIMIZER + SCHEDULER ====
optimizer = optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-4)
scheduler = CosineAnnealingLR(optimizer, T_max=30)

# ==== MIXED PRECISION SCALER ====
scaler = GradScaler('cuda')

# ==== TRAINING LOOP ====
best_val_acc = 0.0
patience, patience_counter = 5, 0
save_path = os.path.join(OUT_DIR, "efficientnet_b4_best.pth")

num_epochs = 50
for epoch in range(num_epochs):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    t0 = time.time()

    for imgs, labels in train_loader:
        imgs, labels = imgs.to(device), labels.to(device)

        optimizer.zero_grad()

        with autocast('cuda'):  # mixed precision
            outputs = model(imgs)
            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item() * imgs.size(0)
        _, preds = outputs.max(1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    train_loss = running_loss / total
    train_acc = correct / total

    # ==== VALIDATION ====
    model.eval()
    v_correct, v_total = 0, 0
    with torch.no_grad():
        for imgs, labels in val_loader:
            imgs, labels = imgs.to(device), labels.to(device)
            with autocast('cuda'):
                outputs = model(imgs)
            _, preds = outputs.max(1)
            v_correct += (preds == labels).sum().item()
            v_total += labels.size(0)
    val_acc = v_correct / v_total

    scheduler.step()

    print(f"Epoch {epoch+1}/{num_epochs} | "
          f"train_loss {train_loss:.4f} train_acc {train_acc:.3f} "
          f"val_acc {val_acc:.3f} time {(time.time()-t0):.1f}s")

    # ==== SAVE BEST ====
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        patience_counter = 0
        torch.save({
            'epoch': epoch+1,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'class_to_idx': train_dataset.class_to_idx,
            'classes': train_dataset.classes
        }, save_path)
        print(" ✅ Saved new best:", save_path)
    else:
        patience_counter += 1
        if patience_counter >= patience:
            print("⏹ Early stopping triggered!")
            break

print("Training finished. Best val acc:", best_val_acc)

from google.colab import drive
drive.mount('/content/drive')

import os
import cv2
import torch
import torch.nn as nn
from torchvision import transforms, models
from PIL import Image
import matplotlib.pyplot as plt

# ==== Paths ====
MODEL_PATH = '/content/drive/MyDrive/PCB_DATASET/output/efficientnet_b4_best.pth'  # new trained model
PCB_USED_PATH = '/content/drive/MyDrive/PCB_DATASET/PCB_USED'   # golden/reference images
TEST_IMG_PATH = '/content/drive/MyDrive/PCB_DATASET/images/Missing_hole/07_missing_hole_06.jpg'  # defected PCB

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

checkpoint = torch.load(MODEL_PATH, map_location=device)
classes = checkpoint['classes']
num_classes = len(classes)

model = models.efficientnet_b4(pretrained=False)
model.classifier[1] = nn.Linear(model.classifier[1].in_features, num_classes)
model.load_state_dict(checkpoint['model_state_dict'])
model = model.to(device)
model.eval()

class_to_idx = checkpoint['class_to_idx']
idx_to_class = {v:k for k,v in class_to_idx.items()}
print("✅ Model loaded with classes:", idx_to_class)

transform = transforms.Compose([
    transforms.Resize((128,128)),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5], [0.5,0.5,0.5])
])

from PIL import Image
import matplotlib.pyplot as plt

def test_roi_image(roi_path, model, class_names, transform, device):
    # Load ROI in color
    img = Image.open(roi_path).convert("RGB")
    img_tensor = transform(img).unsqueeze(0).to(device)

    # Inference
    model.eval()
    with torch.no_grad():
        output = model(img_tensor)
        probs = torch.softmax(output, dim=1).cpu().numpy()[0]
        top3_idx = probs.argsort()[-3:][::-1]

    # Get predictions
    top3 = [(class_names[i], float(probs[i])) for i in top3_idx]
    label, conf = top3[0]

    # Show ROI + Prediction
    plt.imshow(img)
    plt.axis("off")
    plt.title(f"Predicted: {label} ({conf:.2f})")
    plt.show()

    return label, conf, top3


# ==== Example usage ====
roi_path = "/content/drive/MyDrive/PCB_DATASET/ROIs/Open_circuit/testing_oc.png"  # put your ROI image here
label, conf, top3 = test_roi_image(roi_path, model, classes, transform, device)

print("✅ Final Prediction:", label, conf)
print("Top-3 Predictions:", top3)











